plugins {
    id 'java'
}

group = 'yee.pltision'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

project.ext.jomlVersion = "1.10.9"
project.ext.annotationsVersion = "24.0.1"

dependencies {
    implementation project(':processor')
    annotationProcessor project(':processor')

    testAnnotationProcessor project(':processor')

    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // 测试使用
    implementation "org.joml:joml:${jomlVersion}"

    // 生成代码时使用
    implementation 'com.palantir.javapoet:javapoet:0.17.0'
    implementation "org.joml:joml:${jomlVersion}"

}

test {
    useJUnitPlatform()
}
