plugins {
    id 'java'
}

group = 'yee.pltision'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':processor')
    annotationProcessor project(':processor')
    // ★ 关键：为测试编译声明注解处理器依赖
    testAnnotationProcessor project(':processor')

    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
