package yee.pltision.soa.joml;

import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.TypeSpec;
import org.joml.*;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.io.IOException;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

import yee.pltision.soa.annotation.Glue;

public class JomlGlueGenerator {

    private static final List<Class<?>> JOML_CLASSES = Stream.of(
            AxisAngle4d.class,
            AxisAngle4f.class,
            FrustumIntersection.class,
            FrustumRayBuilder.class,
            GeometryUtils.class,
            Interpolationd.class,
            Interpolationf.class,
            Intersectiond.class,
            Intersectionf.class,
            Matrix2d.class,
            Matrix2dc.class,
            Matrix2f.class,
            Matrix2fc.class,
            Matrix3d.class,
            Matrix3dStack.class,
            Matrix3dc.class,
            Matrix3f.class,
            Matrix3fStack.class,
            Matrix3fc.class,
            Matrix3x2d.class,
            Matrix3x2dStack.class,
            Matrix3x2dc.class,
            Matrix3x2f.class,
            Matrix3x2fStack.class,
            Matrix3x2fc.class,
            Matrix4d.class,
            Matrix4dStack.class,
            Matrix4dc.class,
            Matrix4f.class,
            Matrix4fStack.class,
            Matrix4fc.class,
            Matrix4x3d.class,
            Matrix4x3dStack.class,
            Matrix4x3dc.class,
            Matrix4x3f.class,
            Matrix4x3fStack.class,
            Matrix4x3fc.class,
            Options.class,
            PolygonsIntersection.class,
            Quaterniond.class,
            QuaterniondInterpolator.class,
            Quaterniondc.class,
            Quaternionf.class,
            QuaternionfInterpolator.class,
            Quaternionfc.class,
            Random.class,
            RayAabIntersection.class,
            RoundingMode.class,
            SimplexNoise.class,
            Vector2L.class,
            Vector2Lc.class,
            Vector2d.class,
            Vector2dc.class,
            Vector2f.class,
            Vector2fc.class,
            Vector2i.class,
            Vector2ic.class,
            Vector3L.class,
            Vector3Lc.class,
            Vector3d.class,
            Vector3dc.class,
            Vector3f.class,
            Vector3fc.class,
            Vector3i.class,
            Vector3ic.class,
            Vector4L.class,
            Vector4Lc.class,
            Vector4d.class,
            Vector4dc.class,
            Vector4f.class,
            Vector4fc.class,
            Vector4i.class,
            Vector4ic.class
    ).filter(clazz -> {
        String name = clazz.getSimpleName();
        return !name.startsWith("Interpolation") && ( name.endsWith("f") || name.endsWith("d") || name.endsWith("i") || name.endsWith("L") );
    }).toList();

    public static void main(String[] args) throws IOException {
        TypeSpec jomlAnnotation = buildJomlAnnotation();
        String outputPath = args.length > 0 ? args[0] : null;
        JavaFile javaFile = JavaFile.builder("yee.pltision.soa.annotation", jomlAnnotation)
                .addFileComment("Generated by JomlGlueGenerator. Do not edit.")
                .build();
        if (outputPath != null) {
            javaFile.writeTo(new java.io.File(outputPath));
            System.out.println("Written to " + outputPath);
        } else {
            javaFile.writeTo(System.out);
        }
        System.out.println("Generated @Joml annotation with " + JOML_CLASSES.size() + " @Glue entries.");
    }

    private static TypeSpec buildJomlAnnotation() {
        TypeSpec.Builder builder = TypeSpec.annotationBuilder("Joml")
                .addAnnotation(AnnotationSpec.builder(Target.class)
                        .addMember("value", "$T.FIELD", ElementType.class)
                        .addMember("value", "$T.RECORD_COMPONENT", ElementType.class)
                        .build())
                .addAnnotation(AnnotationSpec.builder(Retention.class)
                        .addMember("value", "$T.SOURCE", RetentionPolicy.class)
                        .build());

        for (Class<?> clazz : JOML_CLASSES) {
            builder.addAnnotation(createGlueAnnotation(clazz));
        }

        return builder.build();
    }

    private static AnnotationSpec createGlueAnnotation(Class<?> clazz) {
        String[] fieldNames = getNonStaticFieldNames(clazz);

        AnnotationSpec.Builder glueBuilder = AnnotationSpec.builder(Glue.class)
                .addMember("type", "$T.class", clazz);

        for (String fieldName : fieldNames) {
            glueBuilder.addMember("args", "$S", fieldName);
        }

        return glueBuilder.build();
    }

    /**
     * 获取类的所有非 static 字段名（包括 private）。
     * 这些字段名作为 {@link Glue} 注解的 args，用于 Glue 的代码模板（getField/getFieldToDest/setField）
     * 中作为参数名占位符（$N），并非直接访问字段，因此不需要 public 可见性。
     *
     * <p>排除 JOML 的 {@code properties} 字段（Matrix4d/Matrix4f 中的 {@code protected int properties}），
     * 该字段存储矩阵状态标志位（是否为单位矩阵、正交矩阵等），不是矩阵元素数据，不应参与 SoA 拆解。</p>
     */
    private static String[] getNonStaticFieldNames(Class<?> clazz) {
        List<String> names = new ArrayList<>(16);
        for (Field field : clazz.getDeclaredFields()) {
            if (!Modifier.isStatic(field.getModifiers()) && !"properties".equals(field.getName())) {
                names.add(field.getName());
            }
        }
        return names.toArray(new String[0]);
    }
}
