plugins {
    id 'java-library'
}

group = 'yee.pltision'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // 生成代码
    implementation 'com.palantir.javapoet:javapoet:0.17.0'

    // 可选的Accessor
    implementation "org.joml:joml:${jomlVersion}"

    compileOnly "org.jetbrains:annotations:${annotationsVersion}"

    // 字符串处理
    compileOnly 'cn.hutool:hutool-all:5.8.47'

}
